version: '3.8'
services:
  client:
    image: edvinnordin/shibafencingfrontend:latest
    ports:
      - "3000:80"
    depends_on:
      - server

  server:
    image: edvinnordin/shibafencingbackend:latest
    ports:
      - "8181:8181"
